import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MainClient } from "@/components/wrapper";
import Header from "@/components/home/header";
import Footer from "@/components/home/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.svg" type="image/svg+xml" />
      </head>
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <Header />
        <MainClient>{children}</MainClient>
        <Footer />
      </body>
    </html>
  );
}
