import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/home/header";
import Footer from "@/components/home/footer";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { MainClient } from "@/components/main-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.svg" type="image/svg+xml" />
      </head>
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Header />
          <MainClient>
            <div className="absolute size-64 rounded-full left-12 sm:left-28 top-8 bg-blue-600/10 blur-2xl" />
            <div className="absolute size-48 rounded-full right-12 sm:right-24 top-72 bg-blue-600/15 blur-3xl" />
            {children}
          </MainClient>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
