export const projectsList = [
  {
    title: "Saikindo",
    href: "https://saikindo.co.id",
    isPrimary: true,
    description: `Saikindo company's website containing the company profile, products, and other services.`,
    tools: ["next", "react", "tailwind", "typescript", "shadcn", "zustand"],
    imagePath: "/projects/saikindo-shoot-1.jpg",
  },
  {
    title: "Hadin Al Musri`",
    href: "https://hadinalmusri.com",
    isPrimary: true,
    description: `Hadinalmusri school website located in Pagaden Subang, containing the school profile and other information.`,
    tools: ["next", "react", "tailwind", "typescript", "shadcn", "zustand"],
    imagePath: "/projects/hadinalmusri-shoot-1.jpg",
  },
  {
    title: "Next Jikan",
    href: "https://next-jikan.vercel.app",
    isPrimary: true,
    description: `Nextjs with anime data from public api jikan animae`,
    tools: ["next", "jikan.moe", "react", "tailwind", "typescript", "shadcn", "zustand"],
    imagePath: "/projects/next-jikan-shoot-1.jpg",
  },
  {
    title: "Next Shad",
    href: "https://next-shad-tami.vercel.app",
    isPrimary: true,
    description: `Nextjs with database and storage from vercel, include hosting`,
    tools: ["next", "vercel", "react", "tailwind", "typescript", "shadcn", "zustand"],
    imagePath: "/projects/next-shad-shoot-1.jpg",
  },
  {
    title: "Next Appwrite",
    href: "https://next-appwrite.vercel.app",
    isPrimary: true,
    description: `Nextjs with database and storage from appwrite, and hosted by vercel`,
    tools: ["next", "appwrite", "react", "tailwind", "typescript", "shadcn", "zustand"],
    imagePath: "/projects/next-appwrite-shoot-1.jpg",
  },
  {
    title: "Vite Shop Tami",
    href: "https://vite-shop-tami.vercel.app",
    isPrimary: true,
    description: `Using Vite for a React frontend, with a Node.js and Express backend connected to a MongoDB database, and hosting the project on Vercel.`,
    tools: ["vite", "mongodb", "express", "nodejs", "tailwind", "typescript", "shadcn", "zustand"],
    imagePath: "/projects/vite-shop-tami-shoot-1.jpg",
  },
  {
    title: "Vite Firebase",
    href: "https://vite-firebase-tami.vercel.app",
    isPrimary: true,
    description: `Vite buildtool with database and storage from firebase and hosted by vercel.`,
    tools: ["vite", "firebase", "tailwind", "typescript", "shadcn", "zustand"],
    imagePath: "/projects/vite-firebase-shoot-1.jpg",
  },
  {
    title: "Vite Shad",
    href: "https://vite-shad.vercel.app",
    isPrimary: false,
    description: "Vite buildtool contains components and tips with hosting from vercel.",
    tools: ["html", "css", "javascript", "tailwind", "shadcn", "zustand"],
    imagePath: "/projects/vite-shad-shoot-1.jpg",
  },
  {
    title: "MERN",
    href: "https://tamimern.vercel.app/",
    isPrimary: false,
    // description: `This project involves implementing four todo apps, each with identical functionality but utilizing different tools for their respective implementations. All the apps are designed with a consistent user interface, leveraging ShadCN UI for a cohesive and polished appearance.`,
    description: `This project involves implementing four todo apps, each with identical functionality but utilizing different tools for their respective implementations.`,
    tools: [
      "bcrypt",
      "cloudinary",
      "freesqldatabase",
      "jwt",
      "mongodb",
      "mongoose",
      "multer",
      "mysql",
      "mysql2",
      "notistack",
      "railway",
      "react",
      "react-hot-toast",
      // "redux",
      // "redux rtk",
      // "redux thunk",
      // "sequelize",
      // "shadcn",
      // "sonner",
      // "tailwind",
      // "typescript",
      // "zustand",
    ],
  },
  {
    title: "PublicApi",
    href: "https://tamipublicapi.vercel.app/",
    isPrimary: true,
    description: `The project retrieves data from a public API called OMDB API and presents it in a grid system. It includes features like searching, filtering, and detailed views for each item, offering a comprehensive and user-friendly interface.`,
    tools: [
      "shadcn",
      "zustand",
      "DummyJson",
      "FakestoreApi",
      "JikanAnime",
      "Jsonplaceholder",
      "NewsApi",
      "Reqres",
      "Sisko",
      "TMDB",
      "nextjs",
      "omdbapi",
      "sonner",
      "tailwind",
      "typescript",
    ],
  },
  {
    title: "Sistem Toko",
    href: "https://tamivite.vercel.app/sisko",
    isPrimary: false,
    description: `The project fetches data from a public API called "Sistem Toko" and displays it in a grid system. It includes filtering, searching, sorting, detailed item views, a shopping cart with add/remove options, checkout, and address selection for delivery.`,
    tools: ["react", "tailwind", "sistem-toko", "react-hot-toast"],
  },
  {
    title: "Static Web",
    href: "https://tamivite.vercel.app/html-static-web",
    isPrimary: false,
    description: `These are some simple static websites that I have followed and learned from various YouTube channels and bootcamps.`,
    tools: ["html", "css", "javascript"],
  },
];
